### ISSUE TITLE
Doc: Improve the performance profile documentation specifying the Mandatory attributes under PerformanceProfiles 

### ISSUE THREAD

**Issue by mrniranjan** [openshift-kni/performance-addon-operators#426]
The current documentation of  fields under the PerformanceProfile spec are marked as false under the "Required" .  The Documentation should mark what fields/subset of those fields are required/mandatory/. 

For example in the current performance profile [documentation](https://github.com/openshift-kni/performance-addon-operators/blob/master/docs/performance_profile.md) the fields under CPU are marked as "false" . 

Another example in the case of HugePage which has 2 fields defaultHugepagesSize, pages , it's not clear from the documentation  that if defaultHugepagesSize is specified then pages should also be mandatory field ?. 

Another example is RealTimeKernel where if we mark field "enabled" as true , then the fields under CPU are mandatory, this is not clear from the documentation. 

It would be good if we can mark what fields are mandatory/required  in the documentation.

**Comment by slintes** [comment]
Hey, since I added that doc / its generator, I had a quick look at this.
- the `Required` field is filled based on the `omitempty` json tag on the CRD type definitions, see [0].
- looking at the CRD, seems `omitempty` is set on all fields. So a 1st easy fix would be to remove it for fields which are always mandatory, based on the validation code [1]. The challenge is to keep this in sync.
- The bigger issues are conditional mandatory fields... that would require a bigger change in doc generation I'm afraid. 

[0] https://github.com/openshift-kni/performance-addon-operators/blob/6f860628d0c0920a00ffeabd81f68c89b3ebae00/tools/docs-generator/docs-generator.go#L238
[1] https://github.com/openshift-kni/performance-addon-operators/blob/5474deb877c8abc498880c879adcca26c2596226/pkg/controller/performanceprofile/components/profile/profile.go#L21
